### BITCOIN PRICE ANALYSIS

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

d:\Users\hi\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df=pd.read_csv('Binance_BTCUSDT_2020_minute.csv')

In [3]:
df

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USDT,tradecount
0,1609459140000,2020-12-31 23:59:00,BTC/USDT,28923.66,28952.28,28903.86,28923.63,51.895343,1.501321e+06,860
1,1609459080000,2020-12-31 23:58:00,BTC/USDT,28975.03,28977.10,28923.15,28923.67,36.070975,1.044267e+06,615
2,1609459020000,2020-12-31 23:57:00,BTC/USDT,28975.06,28981.41,28955.35,28975.03,21.327772,6.178355e+05,564
3,1609458960000,2020-12-31 23:56:00,BTC/USDT,28978.91,28988.06,28969.99,28975.06,19.086172,5.530618e+05,570
4,1609458900000,2020-12-31 23:55:00,BTC/USDT,28977.83,28983.62,28956.76,28979.72,15.936455,4.616632e+05,603
...,...,...,...,...,...,...,...,...,...,...
526684,1577837100000,2020-01-01 00:05:00,BTC/USDT,7174.71,7177.14,7173.28,7175.61,33.725000,2.419795e+05,124
526685,1577837040000,2020-01-01 00:04:00,BTC/USDT,7179.10,7179.10,7172.94,7175.25,97.368000,6.986274e+05,193
526686,1577836980000,2020-01-01 00:03:00,BTC/USDT,7177.77,7182.60,7177.00,7181.11,69.330000,4.977934e+05,104
526687,1577836920000,2020-01-01 00:02:00,BTC/USDT,7179.01,7179.01,7175.25,7177.93,99.420000,7.135396e+05,148
526688,1577836860000,2020-01-01 00:01:00,BTC/USDT,7182.43,7182.44,7178.75,7179.01,70.909000,5.091458e+05,140

In [4]:
df.head()

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USDT,tradecount
0,1609459140000,2020-12-31 23:59:00,BTC/USDT,28923.66,28952.28,28903.86,28923.63,51.895343,1.501321e+06,860
1,1609459080000,2020-12-31 23:58:00,BTC/USDT,28975.03,28977.10,28923.15,28923.67,36.070975,1.044267e+06,615
2,1609459020000,2020-12-31 23:57:00,BTC/USDT,28975.06,28981.41,28955.35,28975.03,21.327772,6.178355e+05,564
3,1609458960000,2020-12-31 23:56:00,BTC/USDT,28978.91,28988.06,28969.99,28975.06,19.086172,5.530618e+05,570
4,1609458900000,2020-12-31 23:55:00,BTC/USDT,28977.83,28983.62,28956.76,28979.72,15.936455,4.616632e+05,603

In [5]:
df.tail()

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USDT,tradecount
526684,1577837100000,2020-01-01 00:05:00,BTC/USDT,7174.71,7177.14,7173.28,7175.61,33.725,241979.50880,124
526685,1577837040000,2020-01-01 00:04:00,BTC/USDT,7179.10,7179.10,7172.94,7175.25,97.368,698627.39382,193
526686,1577836980000,2020-01-01 00:03:00,BTC/USDT,7177.77,7182.60,7177.00,7181.11,69.330,497793.35929,104
526687,1577836920000,2020-01-01 00:02:00,BTC/USDT,7179.01,7179.01,7175.25,7177.93,99.420,713539.55348,148
526688,1577836860000,2020-01-01 00:01:00,BTC/USDT,7182.43,7182.44,7178.75,7179.01,70.909,509145.78482,140

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526689 entries, 0 to 526688
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   unix         526689 non-null  int64
 1   date         526689 non-null  object
 2   symbol       526689 non-null  object
 3   open         526689 non-null  float64
 4   high         526689 non-null  float64
 5   low          526689 non-null  float64
 6   close        526689 non-null  float64
 7   Volume BTC   526689 non-null  float64
 8   Volume USDT  526689 non-null  float64
 9   tradecount   526689 non-null  int64
dtypes: float64(6), int64(2), object(2)
memory usage: 40.2+ MB

In [7]:
df.describe()

,unix,open,high,low,close,Volume BTC,Volume USDT,tradecount
count,5.266890e+05,526689.000000,526689.000000,526689.000000,526689.000000,526689.000000,5.266890e+05,526689.000000
mean,1.593638e+12,11064.888930,11070.590997,11058.959931,11064.932102,140.969718,1.356381e+06,580.693386
std,9.123785e+09,4237.990462,4241.026833,4234.719921,4238.058336,302.413363,2.743690e+06,767.469860
min,1.577837e+12,3706.960000,3779.000000,3621.810000,3706.960000,0.000000,0.000000e+00,0.000000
25%,1.585737e+12,8858.020000,8863.180000,8853.180000,8858.020000,30.889878,3.521536e+05,200.000000
50%,1.593638e+12,9692.440000,9696.130000,9688.550000,9692.420000,66.314000,7.125734e+05,379.000000
75%,1.601538e+12,11631.300000,11635.010000,11627.000000,11631.270000,144.964000,1.420788e+06,694.000000
max,1.609459e+12,29290.000000,29300.000000,29249.840000,29293.140000,14204.567000,1.609358e+08,29025.000000

In [ ]:
df.mean()

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(inplace=True)

### DATA ANALYSIS OPERATIONS

In [ ]:
sns.lineplot(x='date', y ='close',data=df)
plt.title('closing price overtime')

##### correlation analysis

In [ ]:
correlation=df[['close' ,'Volume BTC' ,'volume USDT']]
sns.heatmap(correlation, annot=True, cmap='coolwarm')